### ISSUE TITLE
Problem with Twitter Cards

### ISSUE THREAD

**Issue by idleberg** [rbrahul/Awesome-JSON-Viewer#16]
Today I've noticed, that this extension breaks Twitter Cards. Rather than playing a YouTube video shared on Twitter, JSON data for the Twitter Card is revealed.

**Demo**

![kapture 2019-02-20 at 21 39 56](https://user-images.githubusercontent.com/1504938/53122970-460a8700-3558-11e9-8bed-4e8f14f6c529.gif)

Source: https://twitter.com/dontbeafraid/status/1098221550149533696

PS: this only happens on the new Twitter, which is currently available as preview (click "Try the new Twitter" in the user menu)

**Comment by rbrahul** [comment]
Hi @idleberg , I tried to reproduce the issue but was not successful. If you think you still can find the issue please re-open it again.

**Comment by idleberg** [comment]
Yes, the problem persists. I can reproduce it in an incognito tab with no other extensions enabled and also in the new Microsoft Edge. The latter supports Chrome extensions out of the box and I only installed it recently, but haven't used it.

**Comment by idleberg** [comment]
Since the initial example URL is no longer active, here is another one: https://twitter.com/LKrauss1/status/1263247997116137473

You will notice that there's an iFrame loading JSON from https://cards-frame.twitter.com/i/cards/tfw/v1/uc/1263247997116137473. I can think of several solutions to prevent this from happening:

- block all content loaded from `https://cards-frame.twitter.com`
- add wildcard support to the existing URL filters (take a look at the [`wildcard`](https://www.npmjs.com/package/wildcard) package)
- add an option to prevent loading content form an iFrame (probably the weakest solution)

By the way (and this is probably a separate issue), I noticed that the URL filters are probably not working as they should. When I add the URL to that tweet to the list, the iFrame will still display the JSON using your extension. The reason is simple: the content is loaded from a different URL than that of the actual page.

**Comment by RayPS** [comment]
I had the exact same issue, I agree with @idleberg for adding wildcard filter support

**Comment by RayPS** [comment]
<img width="768" alt="Screen Shot 2020-08-05 at 05 13 51" src="https://user-images.githubusercontent.com/1941540/89345700-75746b80-d6da-11ea-9cb1-f6661fe5d1c8.png">
I tried to create a fresh new user with this only one extension installed. Still reproduced.
