### ISSUE TITLE
Ability to use it in incognito window

### ISSUE THREAD

**Issue by jeserkin** [rbrahul/Awesome-JSON-Viewer#20]
At the moment, when I click on JSON Viewer Awesome icon in Chrome Incognito window it will either open or switch to already opened Chrome window and open tab there to work with JSON.

Is there any reason, why same can't be available in Incognito window directly? I know for a fact, that there is a bunch of plugins, that work in Chrome Incognito, without the need of switching to Chrome normal window.

**Comment by rbrahul** [comment]
If you want to use the extension in an incognito window, then from the extension manager you need to enable the incognito mode for this extension. I hope that will help what you want.
