### ISSUE TITLE
Manifest file is missing or unreadable Could not load manifest.

### ISSUE THREAD

**Issue by ravi567** [rbrahul/Awesome-JSON-Viewer#22]
HI: I am trying to install this extension on a computer that has controlled acesss to the Internet. I can't click on Add to chrome. So I downloaded the extension (zip file). I get a message window saying: 
Failed to load extension
Manifest file is missing or unreadable
Could not load manifest.

Wondering if someone else has run into this. I see the manifest.json file in the plublic folder. I have tried pointing to src folder. No luck.

THanks
Ravi

**Comment by tom-cichy-cityos** [comment]
The same. Tried installing npm and building it again, the manifest doesn't load.

**Comment by tom-cichy-cityos** [comment]
Ok, got it. Once you clone the extension:

npm install
npm run buid
npm run chrome-ready

- the last one clean some weird stuff up like incorrect paths etc.
