### ISSUE TITLE
How can I change the theme?

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [rbrahul/Awesome-JSON-Viewer#30]
I am searching for an option to change the theme or colors and I didn't find...

`null` value has a color hard to read

**Comment by rbrahul** [comment]
Hi @JavierSegoviaCordoba ,  I have released a new version (V1.1.2). In this version you will see a newly introduced settings page. You can change your theme from there. Initially I am just offering only 2 theme Dark(Default) and Light, and more will come. I have also fixed the color for null. Now You can also add your own color or style if you know a little bit of CSS. Thanks 🙂
