### ISSUE TITLE
Add collapse levels for json and query feature

### ISSUE THREAD

**Issue by mukh007** [rbrahul/Awesome-JSON-Viewer#32]
This is a good to have feature request to add collapsible entity to the formatted json, this is wery helpful in going through huge json payloads.

See
http://www.bodurov.com/JsonFormatter/

Can we add jq kind of query tab to write jq query and that displays results.

**Comment by rbrahul** [comment]
I have recently released a new version ( V1.1.2). Here you will have a newly introduced settings page. And you can expand or collapse the subtrees with a checkbox. Please give a try. Thanks
