### ISSUE TITLE
Plugin triggering when JSON.parse(document.body.textContent) returns number.

### ISSUE THREAD

**Issue by me-alen** [rbrahul/Awesome-JSON-Viewer#34]
Issue when rendering number in the DOM. The plugin is triggering when there is only numbers in the document.body. Look into the logic using the plugin.

![Screenshot from 2020-02-10 17-56-53](https://user-images.githubusercontent.com/20736818/74149867-cbd28700-4c2e-11ea-9370-f06e490f7b4d.png)

**Comment by rbrahul** [comment]
@me-alen I got your point, This extension tries to find if the page contains only JSON data if yes then it parses it and renders the UI otherwise ignores it. JSON.parse("1") is valid to the Javascript engine. I am not sure what I can do for you. I believe it's not troubling you :)
