### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by spidgorny** [rbrahul/Awesome-JSON-Viewer#35]
I get this in the Console on every page:
```
DevTools failed to parse SourceMap: chrome-extension://iemadiahhbebdklepanmkjenfdebfpfe/static/js/main.6e6198ed.js.map
```
I guess you need to disable sourcemap file or add the .map file to the extension package.

**Comment by rbrahul** [comment]
I have released a new version V1.1.2 recently, the issue should have been fixed already. Thanks 🙂
