### ISSUE TITLE
Add option to change theme by css or add themes

### ISSUE THREAD

**Issue by rafalkasa** [rbrahul/Awesome-JSON-Viewer#4]
It will be very nice if you can add possibility to change colors or maybe add themes.
Something similar what JSON Viewer has. I like bright themes instead of dark and others can have different needs. 

![image](https://user-images.githubusercontent.com/19885116/27375057-3cead2b2-566e-11e7-82eb-379e489c9025.png)

I tested yesterday all available JSON Viewers for Chrome and your is the best one ! Good work !

**Comment by rbrahul** [comment]
@rafalkasa Thanks for your feedback. I will try to bring some themes in new version as soon as possible

**Comment by satishnani** [comment]
@rbrahul hey just wanted to know that how can we change background color or have you merged this branch to master

**Comment by dpliskov** [comment]
It would be great to have a possibility to change font and color

**Comment by rbrahul** [comment]
In the latest version (1.1.2 or later) you have options to change the theme and write your own CSS to style. Enjoy the JSON viewer 🙂
