### ISSUE TITLE
Optimizes color

### ISSUE THREAD

**Issue by 1144388620lq** [rbrahul/Awesome-JSON-Viewer#42]
![image](https://user-images.githubusercontent.com/33059022/81160889-45270f00-8fbd-11ea-9df3-e9dd267d288b.png)

Ultramarine blue see proposed change other colors

**Comment by rbrahul** [comment]
I have updated the extension with some awesome new features like change theme, custom style,
and also reworked on the color code you just mentioned. I hope the new version will meet your expectations. It's still in the approval process by the Chrome Extension team. You will get these features on version 1.1.1 or later. Thanks for staying with me 🙂

**Comment by 1144388620lq** [comment]
thanks
