### ISSUE TITLE
Issue viewing JSON output

### ISSUE THREAD

**Issue by shahidpages** [rbrahul/Awesome-JSON-Viewer#46]
For some reason, I only get to see below when viewing any JSON output. Please suggest the fix.

`{
"success": {
"message": "Welcome to Awesome JSON Viewer.",
"status_code": 200
}
}`

![image](https://user-images.githubusercontent.com/7351647/82374528-cc07cd00-9a3c-11ea-80a0-75480ebcf15e.png)

![image](https://user-images.githubusercontent.com/7351647/82375677-919f2f80-9a3e-11ea-9c7a-4c7d9a8779dd.png)

OSWindows,
Chrome Ver: 81.0.4044.138 (Official Build) (64-bit)

PS: It works fine in the Microsoft Edge browser. The issue is in Chrome browser.

![image](https://user-images.githubusercontent.com/7351647/82375425-340ae300-9a3e-11ea-9d05-4d01d384eb72.png)

**Comment by rbrahul** [comment]
So far I did not receive any issue related yours. But I can guess some facts, one of these might be the reason for you.

1. Maybe you are trying on the incognito window without allowing it for Incognito,
2. You might have installed other similar JSON viewer extensions which can conflict.
3. If you click on the Extension Purple Icon you will see https://user-images.githubusercontent.com/7351647/82375677-919f2f80-9a3e-11ea-9c7a-4c7d9a8779dd.png
You don't need to click on the extension icon. It should work once you reload the page once you install the extension. If you click on that icon the extension page will be opened which shows a general response. Here you can work with your custom JSON in input area and parse it to make a tree or chart for easier debugging and representation.

**Comment by shahidpages** [comment]
Hey Rahu,

1. Maybe you are trying on the incognito window without allowing it for Incognito,

> I am not using Incognito mode and also "Allow in incognito" mode is checked.

2. You might have installed other similar JSON viewer extensions which can conflict.

> No other extension is installed for JSON output viewing. Only this one.

3. If you click on the Extension Purple Icon you will see that page.

> Extension seems to work only when its icon(purple) is clicked not just refresh. And, the output is that one (just success message with status:200)

URL: http://api.openweathermap.org/data/2.5/weather?q=Hyderabad&appid=50b1a45ca4e07a0977c0b3c59fe50243&units=metric

I can jump on to Skype call as per your convenience.

**Comment by innokria** [comment]
Its stopped working in chrome , pls fix it

**Comment by shahidpages** [comment]
@innokria Are you facing same issue as what I reported?

**Comment by innokria** [comment]
Yes viewer not loaded in chrome

**Comment by rbrahul** [comment]
Hi Beautiful People , I have uploaded a new version which V1.1.2. It also brings some new amazing demanded features. Your issue should be fixed automatically if the extension gets updated. Thanks

**Comment by rbrahul** [comment]
@shahidpages if you still have the issue please find me in skype as `rahul.ripan`

**Comment by innokria** [comment]
yep its working now . 
Thanks

**Comment by shahidpages** [comment]
Yup. issue is resolved. Thank you.
