### ISSUE TITLE
Style is being applied to non-json pages

### ISSUE THREAD

**Issue by mdkitzman** [rbrahul/Awesome-JSON-Viewer#48]
With the latest release of the plugin, I can see the ability to customize the style 🎉, however it seems that the style is being applied to, and overriding, the styles for all sorts of other websites including gmail and github.

![image](https://user-images.githubusercontent.com/11448209/82588309-d5398c80-9b57-11ea-8549-f839da764dca.png)

**Comment by koogawa** [comment]
Same issue..!

![image](https://user-images.githubusercontent.com/893643/82619203-3ae94f80-9c10-11ea-9d58-20b936fbe945.png)

**Comment by gamingjoy** [comment]
yes, other websites have strange style, need refresh to view the content

**Comment by heweixi** [comment]
> Same issue..!
> 
> ![image](https://user-images.githubusercontent.com/893643/82619203-3ae94f80-9c10-11ea-9d58-20b936fbe945.png)

same issue +1

**Comment by rbrahul** [comment]
Hi @mdkitzman, @koogawa  @gamingjoy @heweixi  for raising this issue, I have just submitted another version fixing that bug. Sorry from my side for your inconvenience. The review process might take a few hours from the Chrome Webstore team. Thanks for staying with JSON Viewer Awesome.
