### ISSUE TITLE
new Awesome-JSON-Viewer alter all Chrome theme style

### ISSUE THREAD

**Issue by heweixi** [rbrahul/Awesome-JSON-Viewer#49]
when upgrade latest(1.1.2), Options can't hide , when change Select Theme,  refresh all Chrome page ,and change theme, and can't back after Restore Default(also refresh all Chrome page )

ps: Chrome version :版本 83.0.4103.61（正式版本） （64 位）

**Comment by rbrahul** [comment]
Hi @heweixi , I am extremely sorry for your inconvenience. I have just uploaded a new version that is being reviewed by Chrome Webstore. Soon will be published and should fix the issue. Thanks for raising the issue. Thanks for staying with ***Awesome-JSON-Viewer***.  Have a wonderful day 🙂

**Comment by rbrahul** [comment]
Version 1.1.3 has been released.
