### ISSUE TITLE
Download URL has been taken down due to malware.

### ISSUE THREAD

**Issue by Jafnee** [rbrahul/Awesome-JSON-Viewer#60]
The [download URL](https://chrome.google.com/webstore/detail/awesome-json/iemadiahhbebdklepanmkjenfdebfpfe) in the README leads to a 404 page. The extension has been taken off the webstore due to malware detection.

**Comment by Jafnee** [comment]
@rbrahul Was the extension knowingly sold off to some malicious buyer?

**Comment by syedzubair96** [comment]
Well, is there any alternative solution to this? I really need this extension!

**Comment by mfkabir** [comment]
Tried to install crx file to chrome and failed. Showing 'No extension allowed from this site'.

**Comment by couldntcatchthebus** [comment]
Is there any other link for that extension?

**Comment by rbrahul** [comment]
Here is the new version https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc which is completely advertisement free and bug free.

**Comment by rbrahul** [comment]
> Well, is there any alternative solution to this? I really need this extension!

Here is the new version https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc which is completely advertisement free and bug free.
