### ISSUE TITLE
Google Chrome: "This Extension contains malware"

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [rbrahul/Awesome-JSON-Viewer#61]
Google Chrome Extension got disabled because it contains malware.

https://chrome.google.com/webstore/detail/iemadiahhbebdklepanmkjenfdebfpfe

**Comment by akshaysalunke13** [comment]
+1

**Comment by couldntcatchthebus** [comment]
Its 404 now.

**Comment by rbrahul** [comment]
Here is the new version https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc which is completely advertisement free and bug free.

**Comment by akshaysalunke13** [comment]
@rbrahul Could you elaborate on this a bit more? Was the extension hijacked?

**Comment by rbrahul** [comment]
@akshaysalunke13 previously I had sold the ownership of **chrome web-store** for **Awesome JSON Viewer** . Before extension got transferred the buyer promised me the extension will be safe and will contain no malicious script or activities in future. But after 1 month of ownership got changed the owner of that extension might have implemented monetisation and I believe that can be a reason if lot of users complains about.

**Comment by chdh** [comment]
@rbrahul I can't use your extension any more when such things happen. It's a big security risk. I installed it because I thought it was trustworthy open source. But now I see that you have not even published a license. I'm disapointed.

**Comment by sluongng** [comment]
@rbrahul what stopping you from selling this new one also? 

Selling this was a bad decision that betrayed the trust of your users.

**Comment by thepenguinmaster** [comment]
A big disappointment.. putting users at risk for money.
