### ISSUE TITLE
Blocked for Malware? 

### ISSUE THREAD

**Issue by isopropylcyanide** [rbrahul/Awesome-JSON-Viewer#63]
![image](https://user-images.githubusercontent.com/12872673/96131936-6cdcb480-0f17-11eb-83e2-807a403cc659.png)

**Comment by reigenatk** [comment]
same issue here :(

**Comment by NothingSethual** [comment]
same here. Author's updated app (presumably not infected with malware) is here:
https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc

**Comment by isopropylcyanide** [comment]
Thanks for the info @tomcat90 and the updated link @NothingSethual 
I guess we have way too much dependency on this one. Will build from scratch instead. Shouldn't be hard.

Not worth compromising workplace environments with an extension laden with bad influence.

**Comment by rbrahul** [comment]
This is the new extension which doesn't not contain any malware, no unnecessary scripts or marketing advertisements. 
Which safe with no intension to transfer the ownership in future.
[JSON Viewer Pro](https://chrome.google.com/webstore/detail/json-viewer-pro/eifflpmocdbdmepbjaopkkhbfmdgijcc) 
Thanks

**Comment by awkspace** [comment]
@rbrahul Can you please explain what happened? Did you own the other (now malicious) extension?
