### ISSUE TITLE
This extension contains malware. 

### ISSUE THREAD

**Issue by Tawfeekamr** [rbrahul/Awesome-JSON-Viewer#65]
Google chrome disable the extension due to the security issues at the new update `Version 86.0.4240.111 (Official Build) (x86_64)
`

**Comment by rbrahul** [comment]
Please follow that URL where I have described everything what you are looking for. Thanks

https://github.com/rbrahul/Awesome-JSON-Viewer/issues/64#issuecomment-715529497

**Comment by CiriousJoker** [comment]
If anyone wants to security-research the version of this app, here's the latest version that was flagged as being malware. I extracted it from the extension folder.

[JsonViewerAwesome-(with malware)-1.1.5_0.zip](https://github.com/rbrahul/Awesome-JSON-Viewer/files/5469286/JsonViewerAwesome-.with.malware.-1.1.5_0.zip)
! DO NOT INSTALL THIS, FOR ARCHIVAL PURPOSES ONLY !

@rbrahul If you wan't me to delete this, no problem.
