### ISSUE TITLE
Chrome store warning: This Extension contains Malware

### ISSUE THREAD

**Issue by Ryn3r** [rbrahul/Awesome-JSON-Viewer#66]
Apparently Google has detected malware in the extension. Any idea of what's going on?

**Comment by Tiarhai** [comment]
https://github.com/rbrahul/Awesome-JSON-Viewer/issues/63

**Comment by rbrahul** [comment]
Please Delete **JSON viewer Awesome** which has banned by Google because of malicious activities. And use J**SON viwer PRO** instead.
