### ISSUE TITLE
Causes errors in Google DFP

### ISSUE THREAD

**Issue by njt1982** [rbrahul/Awesome-JSON-Viewer#7]
With this extension enabled, I cannot upload creatives to Google DFP.

![image](https://user-images.githubusercontent.com/384976/35386695-dbb4711c-01c4-11e8-9354-bb6bc5c462ff.png)

I get: `Error: Error parsing JSON: SyntaxError: Unexpected token < in JSON at position 0`

With the extension disabled, all is fine.

**Comment by rbrahul** [comment]
From the Settings of the extension you can add Google DFP.'s URL  in the URL filter list and will be ignored while parsing.
